export const communities = [
  {
    id: 3,
    name: "Agarwal",
    sub: "Baniya, Marwari, Jain, Gupta, Goyal",
    slug: "agarwal-matrimony",
  },
  {
    id: 31,
    name: "Arora",
    sub: "Hindu Arora, Punjabi",
    slug: "arora-matrimony",
  },
  {
    id: 34,
    name: "Baniya",
    sub: "Oswal, Khandelwal, Varshney",
    slug: "baniya-matrimony",
  },
  {
    id: 1,
    name: "Brahmin",
    sub: "Smartha, Iyer, Madhwa, Kanyakubja",
    slug: "brahmin-matrimony",
  },
  {
    id: 25,
    name: "Brahmin Bhumihar",
    sub: "Tyagi, Galav",
    slug: "bhumihar-matrimony",
  },
  {
    id: 21,
    name: "Chettiar",
    sub: "Nattukottai, Devanga, Vaniya",
    slug: "chettiar-matrimony",
  },
  { id: 40, name: "Dhoba", sub: "Rajak", slug: "dhoba-matrimony" },
  {
    id: 14,
    name: "Ezhava",
    sub: "Thiyya, Chovvan, Billava",
    slug: "ezhava-matrimony",
  },
  {
    id: 18,
    name: "Gounder",
    sub: "Kongu Vellalar, Nattu",
    slug: "gounder-matrimony",
  },
  { id: 38, name: "Gurmukh", sub: "Hindu Punjabi", slug: "gurmukh-matrimony" },
  {
    id: 8,
    name: "Jat",
    sub: "Hindu Jat, Haryanvi Jat, Deswali",
    slug: "jat-matrimony",
  },
  {
    id: 11,
    name: "Kamma",
    sub: "Chowdary, Naidu, Kammavar",
    slug: "kamma-matrimony",
  },
  {
    id: 6,
    name: "Kayastha",
    sub: "Srivastava, Saxena, Mathur, Nigam",
    slug: "kayastha-matrimony",
  },
  {
    id: 32,
    name: "Khatri",
    sub: "Mehra, Khanna, Kapoor",
    slug: "khatri-matrimony",
  },
  { id: 39, name: "Koli", sub: "Mahadev Koli, Patel", slug: "koli-matrimony" },
  {
    id: 27,
    name: "Kumbhar",
    sub: "Praiapati, Chakravarti",
    slug: "kumbhar-matrimony",
  },
  {
    id: 23,
    name: "Kurmi",
    sub: "Patel, Mahato, Verma",
    slug: "kurmi-matrimony",
  },
  {
    id: 22,
    name: "Kshatriya",
    sub: "Raju, Verma, Saini",
    slug: "kshatriya-matrimony",
  },
  { id: 24, name: "Lohana", sub: "Thakkar, Bhatia", slug: "lohana-matrimony" },
  { id: 29, name: "Mali", sub: "Phule, Saini, Bagwan", slug: "mali-matrimony" },
  {
    id: 7,
    name: "Maratha",
    sub: "96 Kuli, Kunbi, Patil, Deshmukh",
    slug: "maratha-matrimony",
  },
  {
    id: 15,
    name: "Maheshwari",
    sub: "Marwari Maheshwari, Somani",
    slug: "maheshwari-matrimony",
  },
  {
    id: 16,
    name: "Mudaliar",
    sub: "Arcot, Thuluva, Agamudayar",
    slug: "mudaliar-matrimony",
  },
  {
    id: 5,
    name: "Nair",
    sub: "Menon, Pillai, Panicker, Kurup",
    slug: "nair-matrimony",
  },
  {
    id: 19,
    name: "Naidu",
    sub: "Balija, Kapu, Gavara, Telaga",
    slug: "naidu-matrimony",
  },
  {
    id: 17,
    name: "Patel",
    sub: "Leuva, Kadva, Patidar, Anjana",
    slug: "patel-matrimony",
  },
  {
    id: 2,
    name: "Rajput",
    sub: "Chauhan, Rathore, Thakur, Sisodia, Kushwaha",
    slug: "rajput-matrimony",
  },
  {
    id: 10,
    name: "Reddy",
    sub: "Motati, Gudati, Pokanati, Kapu",
    slug: "reddy-matrimony",
  },
  {
    id: 26,
    name: "Saini",
    sub: "Shoorsaini, Bhagirathi",
    slug: "saini-matrimony",
  },
  { id: 33, name: "Sindhi", sub: "Lohana, Amil", slug: "sindhi-matrimony" },
  { id: 37, name: "Sonar", sub: "Sunar, Goldsmith", slug: "sonar-matrimony" },
  { id: 36, name: "Teli", sub: "Sahu, Rathore", slug: "teli-matrimony" },
  { id: 35, name: "Vankar", sub: "Hindu Vankar", slug: "vankar-matrimony" },
  {
    id: 12,
    name: "Vanniyar",
    sub: "Gounder, Padayachi, Palli",
    slug: "vanniyar-matrimony",
  },
  {
    id: 28,
    name: "Vellalar",
    sub: "Pillai, Mudaliar, Gounder",
    slug: "vellalar-matrimony",
  },
  {
    id: 20,
    name: "Vishwakarma",
    sub: "Lohar, Panchal, Sutar, Gajjar",
    slug: "vishwakarma-matrimony",
  },
  {
    id: 13,
    name: "Vysya",
    sub: "Arya Vysya, Komati, Beri",
    slug: "vysya-matrimony",
  },
  {
    id: 4,
    name: "Yadav",
    sub: "Ahir, Gwala, Rao, Krishnaverma",
    slug: "yadav-matrimony",
  },
];


export const generateCommunitiesSchema = (communities: { id: number; name: string; sub: string; slug: string }[]) => ({
  "@context": "https://schema.org",
  "@type": "ItemList",
  itemListElement: communities.map((community, index) => ({
    "@type": "ListItem",
    position: index + 1,
    item: {
      "@type": "Service",
      name: `${community.name} Matrimony`,
      serviceType: "Hindu Matrimony",
      description: `Verified profiles for ${community.name} community (${community.sub}).`,
      url: `https://www.seetharamakalyana.in/communities/${community.slug}`,
    },
  })),
});
