import { BROKERAGE_REGISTRATION_FEE, SUPPORT_EMAIL } from "../../utils/constants";

export type LanguageCode = "en" | "hi" | "kn" | "ta" | "te" | "ml" | "bn";


export const languageNamesOptions = [
  { label: "English", value: "en" },
  { label: "ಕನ್ನಡ (Kannada)", value: "kn" },
  { label: "हिंदी (Hindi)", value: "hi" },
  { label: "தமிழ் (Tamil)", value: "ta" },
  { label: "తెలుగు (Telugu)", value: "te" },
  { label: "മലയാളം (Malayalam)", value: "ml" },
  { label: "বাংলা (Bengali)", value: "bn" },
]


export const translations: Record<LanguageCode, Record<string, string>> = {
  kn: {
    title: "ಸೀತಾ ರಾಮ ಕಲ್ಯಾಣದೊಂದಿಗೆ ಪಾಲುದಾರರಾಗಿ",
    subtitle:
      "ನಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಮ್ಯಾಟ್ರಿಮೋನಿ ಬ್ರೋಕರ್‌ಗಳ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿಕೊಳ್ಳಿ.",
    benefits_title: "ನಿಮ್ಮ ವಿಶೇಷ ಪ್ರಯೋಜನಗಳು",
    benefit_1_strong: "ಲಾಭದಾಯಕ ರೆಫರಲ್ ಬೋನಸ್:",
    benefit_1_text:
      "ನೋಂದಾಯಿಸುವ ಮತ್ತು ನಿಮ್ಮ ಅನನ್ಯ ಕೋಡ್ ಬಳಸುವ ಪ್ರತಿ ಬಳಕೆದಾರರಿಗೆ ಗಣನೀಯ ರೆಫರಲ್ ಬೋನಸ್ ಪಡೆಯಿರಿ. ನೀವು ಹೆಚ್ಚು ರೆಫರ್ ಮಾಡಿದಷ್ಟೂ ಹೆಚ್ಚು ಗಳಿಸುತ್ತೀರಿ!",
    benefit_2_strong: "ನಿಮ್ಮ ಕಂಪನಿಯನ್ನು ಜಾಹೀರಾತು ಮಾಡಿ:",
    benefit_2_text:
      "ನಾವು ವೈಯಕ್ತೀಕರಿಸಿದ ಸೇವೆಗಳನ್ನು ತಪ್ಪಿಸಿ, ಶುದ್ಧ ತಂತ್ರಜ್ಞಾನ ವೇದಿಕೆಯಾಗಿ ಉಳಿಯಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ಬದಲಾಗಿ, ಸೀತಾ ರಾಮ ಕಲ್ಯಾಣ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಕಂಪನಿ ಮತ್ತು ಸಂಪರ್ಕ ಮಾಹಿತಿಯನ್ನು ಜಾಹೀರಾತು ಮಾಡುವ ಮೂಲಕ ನಿಮಗೆ ಬೆಳೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.",
    benefit_3_strong: "ಪಾರದರ್ಶಕ ಟ್ರ್ಯಾಕಿಂಗ್:",
    benefit_3_text:
      "ಒಮ್ಮೆ ನೋಂದಾಯಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಅನನ್ಯ ರೆಫರಲ್ ಕೋಡ್ ಬಳಸಿಕೊಂಡು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಿದ ಎಲ್ಲಾ ಬಳಕೆದಾರರನ್ನು ನೋಡಲು ನೀವು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಪ್ರವೇಶ ಪಡೆಯುತ್ತೀರಿ.",
    contact_support: "ವಿವರವಾದ ಕಮಿಷನ್ ರಚನೆಗಳು ಮತ್ತು ಬೆಂಬಲಕ್ಕಾಗಿ:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "ನಿಮ್ಮ 3-ಹಂತದ ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಪ್ರಕ್ರಿಯೆ",
    step_1_title: "ನೋಂದಣಿ",
    step_1_desc:
      "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ, ಕಂಪನಿ ಮತ್ತು ಪರಿಶೀಲನೆ ವಿವರಗಳೊಂದಿಗೆ (ಐಡಿ ಪ್ರೂಫ್ ಅಪ್‌ಲೋಡ್) ಕೆಳಗಿನ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    step_2_title: "ಪರಿಶೀಲನೆ",
    step_2_desc:
      "ನಮ್ಮ ತಂಡವು ನಿಮ್ಮ ದಾಖಲೆಗಳು ಮತ್ತು ಕಂಪನಿಯ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತದೆ. ಇದು ಸಾಮಾನ್ಯವಾಗಿ 24-48 ಗಂಟೆಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.",
    step_3_title: "ಕೋಡ್ ಮತ್ತು ಹಂಚಿಕೆ",
    step_3_desc:
      "ಒಮ್ಮೆ ಅನುಮೋದಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಅನನ್ಯ ರೆಫರಲ್ ಕೋಡ್ ಅನ್ನು ನೀವು ಸ್ವೀಕರಿಸುತ್ತೀರಿ. ಹಂಚಿಕೊಳ್ಳಲು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ನಿಮ್ಮ ರೆಫರಲ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ!",
    form_title: "ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    section_1_title: "1. ವೈಯಕ್ತಿಕ ಮತ್ತು ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    label_name: "ಪೂರ್ಣ ಹೆಸರು",
    placeholder_name: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು",
    label_email: "ಇಮೇಲ್ ವಿಳಾಸ",
    placeholder_email: "you@example.com",
    label_phone: "ಫೋನ್ ಸಂಖ್ಯೆ (10 ಅಂಕೆಗಳು)",
    placeholder_phone: "ಉದಾಹರಣೆಗೆ, 9876543210",
    section_2_title: "2. ಖಾತೆ ಭದ್ರತೆ",
    label_password: "ಪಾಸ್ವರ್ಡ್",
    placeholder_password: "ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು",
    label_confirm_password: "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    placeholder_confirm_password: "ಪಾಸ್ವರ್ಡ್ ಮರು ನಮೂದಿಸಿ",
    section_3_title: "3. ವ್ಯಾಪಾರ ವಿವರಗಳು",
    label_company_name: "ಕಂಪನಿಯ ಹೆಸರು",
    placeholder_company_name: "ಉದಾಹರಣೆಗೆ, ಎಬಿಸಿ ಮ್ಯಾಟ್ರಿಮೋನಿ ಸೇವೆಗಳು",
    label_address: "ವ್ಯಾಪಾರ ವಿಳಾಸ",
    placeholder_address: "ಪೂರ್ಣ ಅಂಚೆ ವಿಳಾಸ",
    section_4_title: "4. ಪರಿಶೀಲನಾ ದಾಖಲೆ",
    label_id_proof: "ಐಡಿ ಪ್ರೂಫ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (ಆಧಾರ್/ಪ್ಯಾನ್/ಡಿಎಲ್)",
    accept_formats:
      "ಸ್ವೀಕರಿಸಿದ ಸ್ವರೂಪಗಳು: JPG, PNG, PDF. ಪರಿಶೀಲನೆಗಾಗಿ ಇದು ಕಡ್ಡಾಯವಾಗಿದೆ.",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE} ಗೆ ನೋಂದಣಿ ಮಾಡಿ`,
    label_note: "ಸೂಚನೆ",
    label_note_placeholder: "ನಿಮ್ಮ ಸೂಚನೆಯನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ",
    label_community_serve: "ನೀವು ಸೇವೆ ನೀಡುವ ಸಮುದಾಯಗಳು",
    choose_language: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    mother_tongues_serve: "ನೀವು ಸೇವೆ ನೀಡುವ ಮಾತೃಭಾಷೆಗಳು",
  },
  en: {
    title: "Partner with Seetha Rama Kalyana",
    subtitle: "Join our network of trusted Matrimony Brokers.",
    benefits_title: "Your Exclusive Benefits",
    benefit_1_strong: "Lucrative Referral Bonus:",
    benefit_1_text:
      "Receive a substantial referral bonus for every user who registers and uses your unique code. The more you refer, the more you earn!",
    benefit_2_strong: "Advertise Your Company:",
    benefit_2_text:
      "We are committed to remaining a pure tech platform, avoiding personalized services. Instead, we will help you grow by advertising your company and contact information within the Seetha Rama Kalyana app.",
    benefit_3_strong: "Transparent Tracking:",
    benefit_3_text:
      "Once registered, you will gain access to a dashboard to view all users who have registered successfully using your unique referral code.",
    contact_support: "For detailed commission structures and support:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "Your 3-Step Onboarding Process",
    step_1_title: "Registration",
    step_1_desc:
      "Complete the form below with your personal, company, and verification details (ID proof upload).",
    step_2_title: "Verification",
    step_2_desc:
      "Our team will verify your documents and company information. This typically takes 24-48 hours.",
    step_3_title: "Code & Share",
    step_3_desc:
      "Once approved, you will receive your unique referral code. Start sharing and begin tracking your referrals!",
    form_title: "Apply Now",
    section_1_title: "1. Personal & Contact Information",
    label_name: "Full Name",
    placeholder_name: "Your Full Name",
    label_email: "Email Address",
    placeholder_email: "you@example.com",
    label_phone: "Phone Number (10 digits)",
    placeholder_phone: "e.g., 9876543210",
    section_2_title: "2. Account Security",
    label_password: "Password",
    placeholder_password: "Minimum 6 characters",
    label_confirm_password: "Confirm Password",
    placeholder_confirm_password: "Re-enter password",
    section_3_title: "3. Business Details",
    label_company_name: "Company Name",
    placeholder_company_name: "e.g., ABC Matrimony Services",
    label_address: "Business Address",
    placeholder_address: "Full mailing address",
    section_4_title: "4. Verification Document",
    label_id_proof: "Upload ID Proof (Aadhar/PAN/DL)",
    submit_button: `Register for ₹${BROKERAGE_REGISTRATION_FEE}`,
    label_note: "Note",
    label_note_placeholder: "Enter your note here",
    label_community_serve: "Communities You Serve",
    choose_language: "Choose Language",
    mother_tongues_serve: "Mother Tongues You Serve",
  },
  hi: {
    title: "सीता राम कल्याण के साथ साझेदारी करें",
    subtitle: "मैट्रिमोनी ब्रोकर्स के हमारे विश्वसनीय नेटवर्क से जुड़ें।",
    benefits_title: "आपके विशेष लाभ",
    benefit_1_strong: "लाभदायक रेफरल बोनस:",
    benefit_1_text:
      "प्रत्येक उपयोगकर्ता के लिए पर्याप्त रेफरल बोनस प्राप्त करें जो पंजीकरण करता है और आपके विशिष्ट कोड का उपयोग करता है। आप जितना अधिक रेफर करेंगे, उतना अधिक कमाएंगे!",
    benefit_2_strong: "अपनी कंपनी का विज्ञापन करें:",
    benefit_2_text:
      "हम व्यक्तिगत सेवाओं से बचते हुए एक शुद्ध तकनीक मंच बने रहने के लिए प्रतिबद्ध हैं। इसके बजाय, हम सीता राम कल्याण ऐप के भीतर आपकी कंपनी और संपर्क जानकारी का विज्ञापन करके आपको बढ़ने में मदद करेंगे।",
    benefit_3_strong: "पारदर्शी ट्रैकिंग:",
    benefit_3_text:
      "एक बार पंजीकृत होने के बाद, आपको अपने विशिष्ट रेफरल कोड का उपयोग करके सफलतापूर्वक पंजीकृत सभी उपयोगकर्ताओं को देखने के लिए एक डैशबोर्ड तक पहुंच प्राप्त होगी।",
    contact_support: "विस्तृत कमीशन संरचनाओं और समर्थन के लिए:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "आपकी 3-चरणीय ऑनबोर्डिंग प्रक्रिया",
    step_1_title: "पंजीकरण",
    step_1_desc:
      "नीचे दिए गए फॉर्म को अपनी व्यक्तिगत, कंपनी और सत्यापन विवरण (आईडी प्रूफ अपलोड) के साथ भरें।",
    step_2_title: "सत्यापन",
    step_2_desc:
      "हमारी टीम आपके दस्तावेज़ों और कंपनी की जानकारी का सत्यापन करेगी। इसमें आमतौर पर 24-48 घंटे लगते हैं।",
    step_3_title: "कोड और साझा करें",
    step_3_desc:
      "एक बार अनुमोदित होने पर, आपको अपना विशिष्ट रेफरल कोड प्राप्त होगा। साझा करना शुरू करें और अपने रेफरल को ट्रैक करना शुरू करें!",
    form_title: "अभी आवेदन करें",
    section_1_title: "1. व्यक्तिगत और संपर्क जानकारी",
    label_name: "पूरा नाम",
    placeholder_name: "आपका पूरा नाम",
    label_email: "ईमेल पता",
    placeholder_email: "आप@उदाहरण.कॉम",
    label_phone: "फ़ोन नंबर (10 अंक)",
    placeholder_phone: "उदाहरण के लिए, 9876543210",
    section_2_title: "2. खाता सुरक्षा",
    label_password: "पासवर्ड",
    placeholder_password: "न्यूनतम 6 वर्ण",
    label_confirm_password: "पासवर्ड की पुष्टि करें",
    placeholder_confirm_password: "पासवर्ड दोबारा दर्ज करें",
    section_3_title: "3. व्यापार विवरण",
    label_company_name: "कंपनी का नाम",
    placeholder_company_name: "उदाहरण के लिए, एबीसी मैट्रिमोनी सेवाएं",
    label_address: "व्यावसायिक पता",
    placeholder_address: "पूरा डाक पता",
    section_4_title: "4. सत्यापन दस्तावेज़",
    label_id_proof: "आईडी प्रूफ अपलोड करें (आधार/पैन/डीएल)",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE} में पंजीकरण करें`,
    label_note: "टिप्पणी",
    label_note_placeholder: "अपनी टिप्पणी यहाँ दर्ज करें",
    label_community_serve: "आप जिन समुदायों की सेवा करते हैं",
    choose_language: "भाषा चुनें",
    mother_tongues_serve: "आप जिन मातृभाषाओं की सेवा करते हैं",
  },

  ta: {
    title: "சீதா ராமா கல்யாணாவுடன் கூட்டுசேருங்கள்",
    subtitle: "நம்பகமான திருமணத் தரகர்களின் எங்கள் நெட்வொர்க்கில் சேரவும்.",
    benefits_title: "உங்களுக்கான பிரத்தியேக நன்மைகள்",
    benefit_1_strong: "லாபகரமான பரிந்துரை போனஸ்:",
    benefit_1_text:
      "பதிவு செய்து உங்கள் தனிப்பட்ட குறியீட்டைப் பயன்படுத்தும் ஒவ்வொரு பயனருக்கும் கணிசமான பரிந்துரை போனஸைப் பெறுங்கள். நீங்கள் எவ்வளவு பரிந்துரைக்கிறீர்களோ, அவ்வளவு அதிகமாக சம்பாதிக்கலாம்!",
    benefit_2_strong: "உங்கள் நிறுவனத்தை விளம்பரப்படுத்துங்கள்:",
    benefit_2_text:
      "தனிப்பயனாக்கப்பட்ட சேவைகளைத் தவிர்த்து, தூய தொழில்நுட்ப தளமாக இருக்க நாங்கள் கடமைப்பட்டுள்ளோம். மாறாக, சீதா ராமா கல்யாணா செயலிக்குள் உங்கள் நிறுவனம் மற்றும் தொடர்புத் தகவலை விளம்பரப்படுத்துவதன் மூலம் நீங்கள் வளர உதவுவோம்.",
    benefit_3_strong: "வெளிப்படையான கண்காணிப்பு:",
    benefit_3_text:
      "பதிவு செய்தவுடன், உங்கள் தனிப்பட்ட பரிந்துரைக் குறியீட்டைப் பயன்படுத்தி வெற்றிகரமாகப் பதிவு செய்த அனைத்து பயனர்களையும் பார்க்க ஒரு டாஷ்போர்டை அணுகுவீர்கள்.",
    contact_support: "விரிவான கமிஷன் கட்டமைப்புகள் மற்றும் ஆதரவுக்காக:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "உங்கள் 3-படி ஆன்போர்டிங் செயல்முறை",
    step_1_title: "பதிவு",
    step_1_desc:
      "உங்கள் தனிப்பட்ட, நிறுவனம் மற்றும் சரிபார்ப்பு விவரங்களுடன் (அடையாள அட்டை பதிவேற்றம்) கீழே உள்ள படிவத்தை நிரப்பவும்.",
    step_2_title: "சரிபார்ப்பு",
    step_2_desc:
      "எங்கள் குழு உங்கள் ஆவணங்கள் மற்றும் நிறுவனத் தகவலைச் சரிபார்க்கும். இதற்கு வழக்கமாக 24-48 மணிநேரம் ஆகும்.",
    step_3_title: "குறியீடு & பகிர்வு",
    step_3_desc:
      "ஒப்புதல் அளிக்கப்பட்டவுடன், உங்கள் தனிப்பட்ட பரிந்துரைக் குறியீட்டைப் பெறுவீர்கள். பகிரத் தொடங்கி உங்கள் பரிந்துரைகளைக் கண்காணிக்கத் தொடங்குங்கள்!",
    form_title: "இப்போது விண்ணப்பிக்கவும்",
    section_1_title: "1. தனிப்பட்ட மற்றும் தொடர்புத் தகவல்",
    label_name: "முழு பெயர்",
    placeholder_name: "உங்கள் முழு பெயர்",
    label_email: "மின்னஞ்சல் முகவரி",
    placeholder_email: "you@example.com",
    label_phone: "தொலைபேசி எண் (10 இலக்கங்கள்)",
    placeholder_phone: "எ.கா., 9876543210",
    section_2_title: "2. கணக்கு பாதுகாப்பு",
    label_password: "கடவுச்சொல்",
    placeholder_password: "குறைந்தபட்சம் 6 எழுத்துக்கள்",
    label_confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    placeholder_confirm_password: "கடவுச்சொல்லை மீண்டும் உள்ளிடவும்",
    section_3_title: "3. வணிக விவரங்கள்",
    label_company_name: "நிறுவனத்தின் பெயர்",
    placeholder_company_name: "எ.கா., ஏபிசி திருமணச் சேவைகள்",
    label_address: "வணிக முகவரி",
    placeholder_address: "முழு அஞ்சல் முகவரி",
    section_4_title: "4. சரிபார்ப்பு ஆவணம்",
    label_id_proof: "அடையாள அட்டை பதிவேற்றம் (ஆதார்/பான்/ஓட்டுநர் உரிமம்)",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE}க்கு பதிவு செய்யவும்`,
    label_note: "குறிப்பு",
    label_note_placeholder: "உங்கள் குறிப்பை இங்கே உள்ளிடுங்கள்",
    label_community_serve: "நீங்கள் சேவை வழங்கும் சமூகங்கள்",
    choose_language: "மொழியைத் தேர்வுசெய்யவும்",
    mother_tongues_serve: "நீங்கள் சேவை செய்யும் தாய்மொழிகள்",
  },
  te: {
    title: "సీతారామ కళ్యాణతో భాగస్వామ్యం చేసుకోండి",
    subtitle: "విశ్వసనీయ మ్యాట్రిమోనీ బ్రోకర్‌ల మా నెట్‌వర్క్‌లో చేరండి.",
    benefits_title: "మీ ప్రత్యేక ప్రయోజనాలు",
    benefit_1_strong: "లాభదాయక రెఫరల్ బోనస్:",
    benefit_1_text:
      "రిజిస్టర్ చేసుకుని, మీ ప్రత్యేక కోడ్‌ను ఉపయోగించే ప్రతి వినియోగదారుకు గణనీయమైన రెఫరల్ బోనస్‌ను పొందండి. మీరు ఎంత ఎక్కువ మందిని రెఫర్ చేస్తే, అంత ఎక్కువ సంపాదిస్తారు!",
    benefit_2_strong: "మీ కంపెనీని ప్రకటించండి:",
    benefit_2_text:
      "వ్యక్తిగతీకరించిన సేవలను నివారించి, స్వచ్ఛమైన సాంకేతిక వేదికగా ఉండాలని మేము కట్టుబడి ఉన్నాము. బదులుగా, సీతారామ కళ్యాణ యాప్‌లో మీ కంపెనీ మరియు సంప్రదింపు సమాచారాన్ని ప్రకటించడం ద్వారా మీరు వృద్ధి చెందడానికి మేము సహాయం చేస్తాము.",
    benefit_3_strong: "పారదర్శక ట్రాకింగ్:",
    benefit_3_text:
      "రిజిస్టర్ చేసుకున్న తర్వాత, మీ ప్రత్యేక రెఫరల్ కోడ్‌ని ఉపయోగించి విజయవంతంగా రిజిస్టర్ చేసుకున్న వినియోగదారులందరినీ చూడటానికి మీకు డాష్‌బోర్డ్ యాక్సెస్ లభిస్తుంది.",
    contact_support: "వివరణాత్మక కమిషన్ నిర్మాణాలు మరియు మద్దతు కోసం:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "మీ 3-దశల ఆన్‌బోర్డింగ్ ప్రక్రియ",
    step_1_title: "నమోదు",
    step_1_desc:
      "మీ వ్యక్తిగత, కంపెనీ మరియు ధృవీకరణ వివరాలతో (ఐడి ప్రూఫ్ అప్‌లోడ్) దిగువ ఫారమ్‌ను పూర్తి చేయండి.",
    step_2_title: "ధృవీకరణ",
    step_2_desc:
      "మా బృందం మీ పత్రాలు మరియు కంపెనీ సమాచారాన్ని ధృవీకరిస్తుంది. దీనికి సాధారణంగా 24-48 గంటలు పడుతుంది.",
    step_3_title: "కోడ్ & భాగస్వామ్యం",
    step_3_desc:
      "ఆమోదించబడిన తర్వాత, మీరు మీ ప్రత్యేక రెఫరల్ కోడ్‌ను అందుకుంటారు. భాగస్వామ్యం చేయడం ప్రారంభించి, మీ రెఫరల్‌లను ట్రాక్ చేయడం ప్రారంభించండి!",
    form_title: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    section_1_title: "1. వ్యక్తిగత & సంప్రదింపు సమాచారం",
    label_name: "పూర్తి పేరు",
    placeholder_name: "మీ పూర్తి పేరు",
    label_email: "ఇమెయిల్ చిరునామా",
    placeholder_email: "you@example.com",
    label_phone: "ఫోన్ నంబర్ (10 అంకెలు)",
    placeholder_phone: "ఉదా., 9876543210",
    section_2_title: "2. ఖాతా భద్రత",
    label_password: "పాస్వర్డ్",
    placeholder_password: "కనీసం 6 అక్షరాలు",
    label_confirm_password: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    placeholder_confirm_password: "పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి",
    section_3_title: "3. వ్యాపార వివరాలు",
    label_company_name: "కంపెనీ పేరు",
    placeholder_company_name: "ఉదా., ABC మ్యాట్రిమోనీ సేవలు",
    label_address: "వ్యాపార చిరునామా",
    placeholder_address: "పూర్తి పోస్టల్ చిరునామా",
    section_4_title: "4. ధృవీకరణ పత్రం",
    label_id_proof: "ఐడి ప్రూఫ్ అప్‌లోడ్ చేయండి (ఆధార్/పాన్/డిఎల్)",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE}కి నమోదు చేయండి`,
    label_note: "గమనిక",
    label_note_placeholder: "మీ గమనికను ఇక్కడ నమోదు చేయండి",
    label_community_serve: "మీరు సేవలందించే సముదాయాలు",
    choose_language: "భాషను ఎంచుకోండి",
    mother_tongues_serve: "మీరు సేవలందించే మాతృభాషలు",
  },
  ml: {
    title: "സീതാ രാമ കല്യാണയുമായി പങ്കുചേരുക",
    subtitle: "വിശ്വസ്തരായ മാട്രിമോണി ബ്രോക്കർമാരുടെ ഞങ്ങളുടെ ശൃംഖലയിൽ ചേരുക.",
    benefits_title: "നിങ്ങളുടെ പ്രത്യേക ആനുകൂല്യങ്ങൾ",
    benefit_1_strong: "വരുമാനം നൽകുന്ന റഫറൽ ബോണസ്:",
    benefit_1_text:
      "നിങ്ങളുടെ തനതായ കോഡ് ഉപയോഗിച്ച് രജിസ്റ്റർ ചെയ്യുന്ന ഓരോ ഉപയോക്താവിനും ഗണ്യമായ റഫറൽ ബോണസ് നേടുക. നിങ്ങൾ എത്രത്തോളം റഫർ ചെയ്യുന്നുവോ, അത്രത്തോളം നിങ്ങൾ സമ്പാദിക്കും!",
    benefit_2_strong: "നിങ്ങളുടെ കമ്പനിയെ പരസ്യം ചെയ്യുക:",
    benefit_2_text:
      "വ്യക്തിഗത സേവനങ്ങൾ ഒഴിവാക്കി, ഒരു ശുദ്ധമായ സാങ്കേതിക പ്ലാറ്റ്‌ഫോമായി തുടരാൻ ഞങ്ങൾ പ്രതിജ്ഞാബദ്ധരാണ്. പകരം, സീതാ രാമ കല്യാണ ആപ്പിനുള്ളിൽ നിങ്ങളുടെ കമ്പനിയുടെയും ബന്ധപ്പെടാനുള്ള വിവരങ്ങളും പരസ്യം ചെയ്തുകൊണ്ട് വളരാൻ ഞങ്ങൾ നിങ്ങളെ സഹായിക്കും.",
    benefit_3_strong: "സുതാര്യമായ ട്രാക്കിംഗ്:",
    benefit_3_text:
      "രജിസ്റ്റർ ചെയ്തുകഴിഞ്ഞാൽ, നിങ്ങളുടെ തനതായ റഫറൽ കോഡ് ഉപയോഗിച്ച് വിജയകരമായി രജിസ്റ്റർ ചെയ്ത എല്ലാ ഉപയോക്താക്കളെയും കാണാൻ ഒരു ഡാഷ്‌ബോർഡിലേക്ക് നിങ്ങൾക്ക് പ്രവേശനം ലഭിക്കും.",
    contact_support: "വിശദമായ കമ്മീഷൻ ഘടനകൾക്കും പിന്തുണക്കും:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "നിങ്ങളുടെ 3-ഘട്ട ഓൺബോർഡിംഗ് പ്രക്രിയ",
    step_1_title: "രജിസ്ട്രേഷൻ",
    step_1_desc:
      "നിങ്ങളുടെ വ്യക്തിപരമായ, കമ്പനി, വെരിഫിക്കേഷൻ വിവരങ്ങൾ (ഐഡി പ്രൂഫ് അപ്‌ലോഡ്) എന്നിവ നൽകി താഴെയുള്ള ഫോം പൂരിപ്പിക്കുക.",
    step_2_title: "വെരിഫിക്കേഷൻ",
    step_2_desc:
      "ഞങ്ങളുടെ ടീം നിങ്ങളുടെ രേഖകളും കമ്പനി വിവരങ്ങളും പരിശോധിക്കും. ഇതിന് സാധാരണയായി 24-48 മണിക്കൂർ എടുക്കും.",
    step_3_title: "കോഡ് & പങ്കിടുക",
    step_3_desc:
      "അംഗീകാരം ലഭിച്ചുകഴിഞ്ഞാൽ, നിങ്ങളുടെ തനതായ റഫറൽ കോഡ് നിങ്ങൾക്ക് ലഭിക്കും. പങ്കുവെക്കാൻ തുടങ്ങുക, നിങ്ങളുടെ റഫറലുകൾ ട്രാക്ക് ചെയ്യാൻ ആരംഭിക്കുക!",
    form_title: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    section_1_title: "1. വ്യക്തിപരമായ & ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    label_name: "മുഴുവൻ പേര്",
    placeholder_name: "നിങ്ങളുടെ മുഴുവൻ പേര്",
    label_email: "ഇമെയിൽ വിലാസം",
    placeholder_email: "you@example.com",
    label_phone: "ഫോൺ നമ്പർ (10 അക്കങ്ങൾ)",
    placeholder_phone: "ഉദാഹരണത്തിന്, 9876543210",
    section_2_title: "2. അക്കൗണ്ട് സുരക്ഷ",
    label_password: "പാസ്‌വേഡ്",
    placeholder_password: "കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ",
    label_confirm_password: "പാസ്‌വേഡ് ഉറപ്പാക്കുക",
    placeholder_confirm_password: "പാസ്‌വേഡ് വീണ്ടും നൽകുക",
    section_3_title: "3. ബിസിനസ്സ് വിവരങ്ങൾ",
    label_company_name: "കമ്പനിയുടെ പേര്",
    placeholder_company_name: "ഉദാഹരണത്തിന്, എബിസി മാട്രിമോണി സർവീസസ്",
    label_address: "ബിസിനസ്സ് വിലാസം",
    placeholder_address: "പൂർണ്ണമായ തപാൽ വിലാസം",
    section_4_title: "4. വെരിഫിക്കേഷൻ രേഖ",
    label_id_proof: "ഐഡി പ്രൂഫ് അപ്‌ലോഡ് ചെയ്യുക (ആധാർ/പാൻ/ഡിഎൽ)",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE}യ്ക്ക് രജിസ്റ്റർ ചെയ്യുക`,
    label_note: "കുറിപ്പ്",
    label_note_placeholder: "നിങ്ങളുടെ കുറിപ്പ് ഇവിടെ നൽകുക",
    label_community_serve: "നിങ്ങൾ സേവനം നൽകുന്ന സമൂഹങ്ങൾ",
    choose_language: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    mother_tongues_serve: "നിങ്ങൾ സേവനം നൽകുന്ന മാതൃഭാഷകൾ",
  },
  bn: {
    title: "সীতা রাম কল্যাণের সাথে অংশীদার হন",
    subtitle: "আমাদের বিশ্বস্ত ম্যাট্রিমনি ব্রোকারদের নেটওয়ার্কে যোগ দিন।",
    benefits_title: "আপনার একচেটিয়া সুবিধাগুলি",
    benefit_1_strong: "লাভজনক রেফারেল বোনাস:",
    benefit_1_text:
      "আপনার অনন্য কোড ব্যবহার করে রেজিস্ট্রেশন করা প্রতিটি ব্যবহারকারীর জন্য যথেষ্ট রেফারেল বোনাস পান। আপনি যত বেশি রেফার করবেন, তত বেশি আয় করবেন!",
    benefit_2_strong: "আপনার কোম্পানির বিজ্ঞাপন দিন:",
    benefit_2_text:
      "আমরা ব্যক্তিগত পরিষেবাগুলি এড়িয়ে একটি বিশুদ্ধ প্রযুক্তি প্ল্যাটফর্ম হিসাবে থাকতে প্রতিশ্রুতিবদ্ধ। পরিবর্তে, আমরা সীতা রাম কল্যাণ অ্যাপের মধ্যে আপনার কোম্পানি এবং যোগাযোগের তথ্য বিজ্ঞাপন দিয়ে আপনাকে বেড়ে উঠতে সাহায্য করব।",
    benefit_3_strong: "স্বচ্ছ ট্র্যাকিং:",
    benefit_3_text:
      "একবার নিবন্ধিত হলে, আপনার অনন্য রেফারেল কোড ব্যবহার করে সফলভাবে নিবন্ধিত সমস্ত ব্যবহারকারীদের দেখতে আপনি একটি ড্যাশবোর্ডে অ্যাক্সেস পাবেন।",
    contact_support: "বিস্তারিত কমিশন কাঠামো এবং সহায়তার জন্য:",
    contact_button: `${SUPPORT_EMAIL}`,
    onboarding_title: "আপনার ৩-ধাপে অনবোর্ডিং প্রক্রিয়া",
    step_1_title: "নিবন্ধন",
    step_1_desc:
      "আপনার ব্যক্তিগত, কোম্পানি এবং যাচাইকরণের বিবরণ (আইডি প্রুফ আপলোড) সহ নীচের ফর্মটি পূরণ করুন।",
    step_2_title: "যাচাইকরণ",
    step_2_desc:
      "আমাদের টিম আপনার নথি এবং কোম্পানির তথ্য যাচাই করবে। এটি সাধারণত ২৪-৪৮ ঘন্টা সময় নেয়।",
    step_3_title: "কোড ও শেয়ার করুন",
    step_3_desc:
      "একবার অনুমোদিত হলে, আপনি আপনার অনন্য রেফারেল কোড পাবেন। শেয়ার করা শুরু করুন এবং আপনার রেফারেলগুলি ট্র্যাক করা শুরু করুন!",
    form_title: "এখনই আবেদন করুন",
    section_1_title: "১. ব্যক্তিগত ও যোগাযোগের তথ্য",
    label_name: "পুরো নাম",
    placeholder_name: "আপনার পুরো নাম",
    label_email: "ইমেল ঠিকানা",
    placeholder_email: "you@example.com",
    label_phone: "ফোন নম্বর (১০ সংখ্যা)",
    placeholder_phone: "যেমন, 9876543210",
    section_2_title: "২. অ্যাকাউন্ট সুরক্ষা",
    label_password: "পাসওয়ার্ড",
    placeholder_password: "কমপক্ষে ৬টি অক্ষর",
    label_confirm_password: "পাসওয়ার্ড নিশ্চিত করুন",
    placeholder_confirm_password: "পাসওয়ার্ড আবার প্রবেশ করান",
    section_3_title: "৩. ব্যবসার বিবরণ",
    label_company_name: "কোম্পানির নাম",
    placeholder_company_name: "যেমন, এবিসি ম্যাট্রিমনি সার্ভিসেস",
    label_address: "ব্যবসার ঠিকানা",
    placeholder_address: "সম্পূর্ণ ডাক ঠিকানা",
    section_4_title: "৪. যাচাইকরণ নথি",
    label_id_proof: "আইডি প্রুফ আপলোড করুন (আধার/প্যান/ডিএল)",
    submit_button: `₹${BROKERAGE_REGISTRATION_FEE} দিয়ে নিবন্ধন করুন`,
    label_note: "নোট",
    label_note_placeholder: "আপনার নোট এখানে লিখুন",
    label_community_serve: "আপনি যেসব সম্প্রদায়ের সেবা দেন",
    choose_language: "ভাষা নির্বাচন করুন",
    mother_tongues_serve: "আপনি যে মাতৃভাষাগুলিতে সেবা দেন",
  },
};
