export const maritalOptions = [
    { label: 'Unmarried', value: 'Unmarried' },
    { label: 'Widowed', value: 'Widowed' },
    { label: 'Divorced', value: 'Divorced' },
    { label: 'Separated', value: 'Separated' },
];

export const parentStatus = [
    { label: 'Alive', value: 'Alive' },
    { label: 'Deceased', value: 'Deceased' },
]

export const familyStatus = [
    { label: 'Lower Middle Class', value: 'Lower Middle Class' },
    { label: 'Middle Class', value: 'Middle Class' },
    { label: 'Upper Middle Class', value: 'Upper Middle Class' },
    { label: 'Rich', value: 'Rich' },
]
export const countryOptions = [
    { label: 'India', value: 'India' },
    { label: 'Afghanistan', value: 'Afghanistan' },
    { label: 'Albania', value: 'Albania' },
    { label: 'Algeria', value: 'Algeria' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armenia', value: 'Armenia' },
    { label: 'Australia', value: 'Australia' },
    { label: 'Austria', value: 'Austria' },
    { label: 'Azerbaijan', value: 'Azerbaijan' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bahrain', value: 'Bahrain' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Belarus', value: 'Belarus' },
    { label: 'Belgium', value: 'Belgium' },
    { label: 'Belize', value: 'Belize' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bhutan', value: 'Bhutan' },
    { label: 'Bolivia', value: 'Bolivia' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
    { label: 'Botswana', value: 'Botswana' },
    { label: 'Brazil', value: 'Brazil' },
    { label: 'Brunei Darussalam', value: 'Brunei Darussalam' },
    { label: 'Bulgaria', value: 'Bulgaria' },
    { label: 'Burkina Faso', value: 'Burkina Faso' },
    { label: 'Burundi', value: 'Burundi' },
    { label: 'Cabo Verde', value: 'Cabo Verde' },
    { label: 'Cambodia', value: 'Cambodia' },
    { label: 'Cameroon', value: 'Cameroon' },
    { label: 'Canada', value: 'Canada' },
    { label: 'Central African Republic', value: 'Central African Republic' },
    { label: 'Chad', value: 'Chad' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Colombia', value: 'Colombia' },
    { label: 'Comoros', value: 'Comoros' },
    { label: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)' },
    { label: 'Congo (Democratic Republic of the)', value: 'Congo (Democratic Republic of the)' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Croatia', value: 'Croatia' },
    { label: 'Cuba', value: 'Cuba' },
    { label: 'Cyprus', value: 'Cyprus' },
    { label: 'Czechia (Czech Republic)', value: 'Czechia (Czech Republic)' },
    { label: 'Denmark', value: 'Denmark' },
    { label: 'Djibouti', value: 'Djibouti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'Dominican Republic', value: 'Dominican Republic' },
    { label: 'Ecuador', value: 'Ecuador' },
    { label: 'Egypt', value: 'Egypt' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
    { label: 'Eritrea', value: 'Eritrea' },
    { label: 'Estonia', value: 'Estonia' },
    { label: 'Eswatini (fmr. "Swaziland")', value: 'Eswatini (fmr. "Swaziland")' },
    { label: 'Ethiopia', value: 'Ethiopia' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Finland', value: 'Finland' },
    { label: 'France', value: 'France' },
    { label: 'Gabon', value: 'Gabon' },
    { label: 'Gambia', value: 'Gambia' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Germany', value: 'Germany' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'Greece', value: 'Greece' },
    { label: 'Grenada', value: 'Grenada' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guinea', value: 'Guinea' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
    { label: 'Guyana', value: 'Guyana' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hungary', value: 'Hungary' },
    { label: 'Iceland', value: 'Iceland' },
    { label: 'Indonesia', value: 'Indonesia' },
    { label: 'Iran', value: 'Iran' },
    { label: 'Iraq', value: 'Iraq' },
    { label: 'Ireland', value: 'Ireland' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Italy', value: 'Italy' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japan', value: 'Japan' },
    { label: 'Jordan', value: 'Jordan' },
    { label: 'Kazakhstan', value: 'Kazakhstan' },
    { label: 'Kenya', value: 'Kenya' },
    { label: 'Kiribati', value: 'Kiribati' },
    { label: 'Korea (North)', value: 'Korea (North)' },
    { label: 'Korea (South)', value: 'Korea (South)' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
    { label: 'Laos', value: 'Laos' },
    { label: 'Latvia', value: 'Latvia' },
    { label: 'Lebanon', value: 'Lebanon' },
    { label: 'Lesotho', value: 'Lesotho' },
    { label: 'Liberia', value: 'Liberia' },
    { label: 'Libya', value: 'Libya' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lithuania', value: 'Lithuania' },
    { label: 'Luxembourg', value: 'Luxembourg' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malawi', value: 'Malawi' },
    { label: 'Malaysia', value: 'Malaysia' },
    { label: 'Maldives', value: 'Maldives' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marshall Islands', value: 'Marshall Islands' },
    { label: 'Mauritania', value: 'Mauritania' },
    { label: 'Mauritius', value: 'Mauritius' },
    { label: 'Mexico', value: 'Mexico' },
    { label: 'Micronesia (Federated States of)', value: 'Micronesia (Federated States of)' },
    { label: 'Moldova', value: 'Moldova' },
    { label: 'Monaco', value: 'Monaco' },
    { label: 'Mongolia', value: 'Mongolia' },
    { label: 'Montenegro', value: 'Montenegro' },
    { label: 'Morocco', value: 'Morocco' },
    { label: 'Mozambique', value: 'Mozambique' },
    { label: 'Myanmar (fmr. Burma)', value: 'Myanmar (fmr. Burma)' },
    { label: 'Namibia', value: 'Namibia' },
    { label: 'Nauru', value: 'Nauru' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Netherlands', value: 'Netherlands' },
    { label: 'New Zealand', value: 'New Zealand' },
    { label: 'Nicaragua', value: 'Nicaragua' },
    { label: 'Niger', value: 'Niger' },
    { label: 'Nigeria', value: 'Nigeria' },
    { label: 'North Macedonia', value: 'North Macedonia' },
    { label: 'Norway', value: 'Norway' },
    { label: 'Oman', value: 'Oman' },
    { label: 'Pakistan', value: 'Pakistan' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Panama', value: 'Panama' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea' },
    { label: 'Paraguay', value: 'Paraguay' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Philippines', value: 'Philippines' },
    { label: 'Poland', value: 'Poland' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Qatar', value: 'Qatar' },
    { label: 'Romania', value: 'Romania' },
    { label: 'Russia', value: 'Russia' },
    { label: 'Rwanda', value: 'Rwanda' },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia', value: 'Saint Lucia' },
    { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa', value: 'Samoa' },
    { label: 'San Marino', value: 'San Marino' },
    { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serbia', value: 'Serbia' },
    { label: 'Seychelles', value: 'Seychelles' },
    { label: 'Sierra Leone', value: 'Sierra Leone' },
    { label: 'Singapore', value: 'Singapore' },
    { label: 'Slovakia', value: 'Slovakia' },
    { label: 'Slovenia', value: 'Slovenia' },
    { label: 'Solomon Islands', value: 'Solomon Islands' },
    { label: 'Somalia', value: 'Somalia' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'South Korea', value: 'South Korea' },
    { label: 'South Sudan', value: 'South Sudan' },
    { label: 'Spain', value: 'Spain' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'Sudan', value: 'Sudan' },
    { label: 'Suriname', value: 'Suriname' },
    { label: 'Sweden', value: 'Sweden' },
    { label: 'Switzerland', value: 'Switzerland' },
    { label: 'Syria', value: 'Syria' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Tajikistan', value: 'Tajikistan' },
    { label: 'Tanzania', value: 'Tanzania' },
    { label: 'Thailand', value: 'Thailand' },
    { label: 'Timor-Leste', value: 'Timor-Leste' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Tonga', value: 'Tonga' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
    { label: 'Tunisia', value: 'Tunisia' },
    { label: 'Turkey', value: 'Turkey' },
    { label: 'Turkmenistan', value: 'Turkmenistan' },
    { label: 'Tuvalu', value: 'Tuvalu' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Ukraine', value: 'Ukraine' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'United States', value: 'United States' },
    { label: 'Uruguay', value: 'Uruguay' },
    { label: 'Uzbekistan', value: 'Uzbekistan' },
    { label: 'Vanuatu', value: 'Vanuatu' },
    { label: 'Vatican City', value: 'Vatican City' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Vietnam', value: 'Vietnam' },
    { label: 'Yemen', value: 'Yemen' },
    { label: 'Zambia', value: 'Zambia' },
    { label: 'Zimbabwe', value: 'Zimbabwe' },
]

export const rashiOptions = [
    { label: 'Mesha (Aries)', value: 'Mesh' },
    { label: 'Vrishabha (Taurus)', value: 'Vrishabh' },
    { label: 'Mithuna (Gemini)', value: 'Mithun' },
    { label: 'Karkataka (Cancer)', value: 'Karka' },
    { label: 'Simha (Leo)', value: 'Simha' },
    { label: 'Kanya (Virgo)', value: 'Kanya' },
    { label: 'Tula (Libra)', value: 'Tula' },
    { label: 'Vrischika (Scorpio)', value: 'Vrischik' },
    { label: 'Dhanu (Sagittarius)', value: 'Dhanu' },
    { label: 'Makara (Capricorn)', value: 'Makar' },
    { label: 'Kumbha (Aquarius)', value: 'Kumbh' },
    { label: 'Meena (Pisces)', value: 'Meen' },
    { label: '---- Not Sure ----', value: 'Not Sure' },

];

export const nakshatraOptions = [
    { label: 'Ashwini', value: 'Ashwini' },
    { label: 'Bharani', value: 'Bharani' },
    { label: 'Krittika', value: 'Krittika' },
    { label: 'Rohini', value: 'Rohini' },
    { label: 'Mrigashira', value: 'Mrigashira' },
    { label: 'Ardra', value: 'Ardra' },
    { label: 'Punarvasu', value: 'Punarvasu' },
    { label: 'Pushya', value: 'Pushya' },
    { label: 'Ashlesha', value: 'Ashlesha' },
    { label: 'Magha', value: 'Magha' },
    { label: 'Purva Phalguni', value: 'Purva Phalguni' },
    { label: 'Uttara Phalguni', value: 'Uttara Phalguni' },
    { label: 'Hasta', value: 'Hasta' },
    { label: 'Chitra', value: 'Chitra' },
    { label: 'Swati', value: 'Swati' },
    { label: 'Vishakha', value: 'Vishakha' },
    { label: 'Anuradha', value: 'Anuradha' },
    { label: 'Jyeshtha', value: 'Jyeshtha' },
    { label: 'Mula', value: 'Mula' },
    { label: 'Purva Ashadha', value: 'Purva Ashadha' },
    { label: 'Uttara Ashadha', value: 'Uttara Ashadha' },
    { label: 'Shravana', value: 'Shravana' },
    { label: 'Dhanishta', value: 'Dhanishta' },
    { label: 'Shatabhisha', value: 'Shatabhisha' },
    { label: 'Purva Bhadrapada', value: 'Purva Bhadrapada' },
    { label: 'Uttara Bhadrapada', value: 'Uttara Bhadrapada' },
    { label: 'Revati', value: 'Revati' },
    { label: '---- Not Sure ----', value: 'Not Sure' },

];

export const heightOptions = [
    { label: "4'0\" (122 cm)", value: "4'0\"" },
    { label: "4'1\" (125 cm)", value: "4'1\"" },
    { label: "4'2\" (127 cm)", value: "4'2\"" },
    { label: "4'3\" (130 cm)", value: "4'3\"" },
    { label: "4'4\" (132 cm)", value: "4'4\"" },
    { label: "4'5\" (135 cm)", value: "4'5\"" },
    { label: "4'6\" (137 cm)", value: "4'6\"" },
    { label: "4'7\" (140 cm)", value: "4'7\"" },
    { label: "4'8\" (142 cm)", value: "4'8\"" },
    { label: "4'9\" (145 cm)", value: "4'9\"" },
    { label: "4'10\" (147 cm)", value: "4'10\"" },
    { label: "4'11\" (150 cm)", value: "4'11\"" },
    { label: "5'0\" (152 cm)", value: "5'0\"" },
    { label: "5'1\" (155 cm)", value: "5'1\"" },
    { label: "5'2\" (157 cm)", value: "5'2\"" },
    { label: "5'3\" (160 cm)", value: "5'3\"" },
    { label: "5'4\" (163 cm)", value: "5'4\"" },
    { label: "5'5\" (165 cm)", value: "5'5\"" },
    { label: "5'6\" (168 cm)", value: "5'6\"" },
    { label: "5'7\" (170 cm)", value: "5'7\"" },
    { label: "5'8\" (173 cm)", value: "5'8\"" },
    { label: "5'9\" (175 cm)", value: "5'9\"" },
    { label: "5'10\" (178 cm)", value: "5'10\"" },
    { label: "5'11\" (180 cm)", value: "5'11\"" },
    { label: "6'0\" (183 cm)", value: "6'0\"" },
    { label: "6'1\" (185 cm)", value: "6'1\"" },
    { label: "6'2\" (188 cm)", value: "6'2\"" },
    { label: "6'3\" (191 cm)", value: "6'3\"" },
    { label: "6'4\" (193 cm)", value: "6'4\"" },
    { label: "6'5\" (196 cm)", value: "6'5\"" },
    { label: "6'6\" (198 cm)", value: "6'6\"" },
];


export const genderOptions = [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
];

export const employedInOptions = [
    { label: "Private", value: "Private" },
    { label: "Government", value: "Government" },
    { label: 'Business', value: 'Business' },
    { label: 'Defence', value: 'Defence' },
    { label: "Self Employed", value: "Self Employed" },
    { label: "Not Working", value: "Not Working" },
];

export const dietOptions = [
    { label: "Vegetarian", value: "Vegetarian" },
    { label: "Non-Vegetarian", value: "Non-Vegetarian" },
    { label: "Eggetarian", value: "Eggetarian" },
]



export const residingOptions = [
    { label: "Indian", value: "Indian" },
    { label: "NRI", value: "NRI" },
]

export const subCasteOptions = [
    { label: 'Smartha', value: 'Male' },
    { label: 'Madhwa/Vaishnava', value: 'Madhwa' },
    { label: 'Iyer', value: 'Iyer' },
    { label: 'Sri Vaishnava/Iyengar', value: 'Iyengar' },
    { label: 'Other', value: 'Other' },
];

export const motherTongueOptions = [
    { label: 'Kannada', value: 'Kannada' },
    { label: 'Tulu', value: 'Tulu' },
    { label: 'Hindi', value: 'Hindi' },
    { label: 'Tamil', value: 'Tamil' },
    { label: 'Telugu', value: 'Telugu' },
    { label: 'Malayalam', value: 'Malayalam' },
];

export const createdByOptions = [
    { label: 'Self', value: 'Self' },
    { label: 'Parent', value: 'Parent' },
    { label: 'Sibling', value: 'Sibling' },
    { label: 'Relative/Friend', value: 'Friend' },
];

export const qualificationOptions = [
    { label: "10th", value: "10th" },
    { label: "12th", value: "12th" },
    { label: "Diploma", value: "diploma" },
    // Bachelor Degrees
    { label: "B.Sc (Science)", value: "bsc" },
    { label: "B.A (Arts)", value: "ba" },
    { label: "B.Com (Commerce)", value: "bcom" },
    { label: "B.Tech / B.E (Engineering)", value: "btech" },
    { label: "BBA (Business Administration)", value: "bba" },
    { label: "BCA (Computer Applications)", value: "bca" },

    // Master Degrees
    { label: "M.Sc (Science)", value: "msc" },
    { label: "M.A (Arts)", value: "ma" },
    { label: "M.Com (Commerce)", value: "mcom" },
    { label: "M.Tech / M.E (Engineering)", value: "mtech" },
    { label: "MBA (Business Administration)", value: "mba" },
    { label: "MCA (Computer Applications)", value: "mca" },
    { label: "PhD", value: "phd" },
    { label: "Other", value: "other" }
]


export const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const user_login_token = 'kalyanam_token'


export const formDefaultVals = {
    fullName: '',
    relationshipStatus: '',
    password: '',
    confirmPassword: '',
    subCaste: '',
    gotra: '',
    mobile: '',
    alternateMob: '',
    gender: '',
    motherTongue: '',
    dob: null,
    profileCreatedBy: '',
    email: '',
    qualification: '',
    images: [],
}